!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!   COPYRIGHT 2018
!
!   PROGRAM:  MAIN.F
!   LANGUAGE: FORTRAN 95
!
!   PURPOSE:  ADVENT OF CODE 2018 DAY 1
!   INPUT:    INPUT.DAT
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

PROGRAM ADDMAIN
  IMPLICIT NONE
  DOUBLE PRECISION :: CURRDISP, NEWDISP
  LOGICAL :: FILEEXIST
  INTEGER :: IO
  INQUIRE(FILE='input.dat', EXIST=FILEEXIST)
  IF (FILEEXIST .eqv. .TRUE.) THEN !INPUT VALIDATION
    OPEN(UNIT=24, FILE='input.dat')
  ELSE
    WRITE(*,*) 'NO INPUT FILE'
  END IF
  CURRDISP = 0 !INITIAL VALUE OF 0
  DO
    READ(UNIT=24,FMT=*,IOSTAT=IO) NEWDISP
    IF (IO/=0) EXIT
    CURRDISP = CURRDISP + NEWDISP
  END DO
  WRITE(*,*) CURRDISP
  CLOSE(24)
END PROGRAM
